/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epg;

/**
 *
 * @author BunnyRailgun
 */
public enum LanguagePropertyType {
    //FILE TOOLBAR
    TITLE_WINDOW,
    TOOLTIP_NEW_PORTFOLIO,
    TOOLTIP_LOAD_PORTFOLIO,
    TOOLTIP_SAVE_PORTFOLIO,
    TOOLTIP_SAVEAS_PORTFOLIO,
    TOOLTIP_EXPORT_PORTFOLIO,
    TOOLTIP_EXIT,
    
    //SITE TOOLBAR
    TOOLTIP_ADD_PAGE,
    TOOLTIP_REMOVE_PAGE,
    
    //COMPONENT TOOLBAR
    TOOLTIP_ADD_TEXT_COMPONENT,
    TOOLTIP_ADD_IMAGE_COMPONENT,
    TOOLTIP_ADD_SS_COMPONENT,
    TOOLTIP_ADD_VIDEO_COMPONENT,
    TOOLTIP_EDIT_COMPONENT,
    TOOLTIP_REMOVE_COMPONENT,
    
    TOOLTIP_ADD_LIST,
    TOOLTIP_REMOVE_LIST,
    TOOLTIP_HYPERLINK,
    
    DEFAULT_PORFOLIO_TITLE,
    LABEL_PAGE_TITLE,
    
    //SLIDE SHOW MAKER
    // APPLICATION TOOLTIPS FOR BUTTONS
    TOOLTIP_NEW_SLIDE_SHOW,
    TOOLTIP_LOAD_SLIDE_SHOW,
    TOOLTIP_SAVE_SLIDE_SHOW,
    TOOLTIP_VIEW_SLIDE_SHOW,
    TOOLTIP_ADD_SLIDE,
    TOOLTIP_REMOVE_SLIDE,
    TOOLTIP_MOVE_UP,
    TOOLTIP_MOVE_DOWN,
    TOOLTIP_PREVIOUS_SLIDE,
    TOOLTIP_NEXT_SLIDE,
    
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_SLIDE_SHOW_TITLE,
    
    // UI LABELS
    LABEL_CAPTION,
    LABEL_SLIDESHOW_TITLE,
      
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_DATA_FILE_LOADING,
    ERROR_PROPERTIES_FILE_LOADING,
    ERROR_NO_SLIDESHOW_IMAGES,
    ERROR_UNEXPECTED
}
